# Generated by Django 5.2.17 on 2026-09-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_id', models.CharField(max_length=255)),
                ('act_title', models.CharField(max_length=500)),
                ('section_number', models.CharField(max_length=50)),
                ('section_title', models.CharField(max_length=500)),
                ('chapter', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
                ('status', models.CharField(blank=True, max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
            ],
        ),
    ]
