# Generated by Django 5.2.17 on 2026-09-30 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legaldata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='legaldata.legaldocument')),
            ],
        ),
    ]
